---
- name: create mirror dir
  file:
    path: "{{ archive_root }}/images/"
    state: absent
  when: clear_image_cache == 'True'

- name: create mirror dir
  file:
    path: "{{ archive_root }}/images/"
    state: directory

- name: pull all 
  command: "docker pull {{ item }}"
  with_items:
    - "{{ images_to_archive }}"

- name: archive 
  command: "docker save -o {{ archive_root }}/images/{{ item|replace('/','_') }}.tar {{ item }}"
  with_items:
    - "{{ images_to_archive }}"

